---
title: "Metadata"
author: "Indra Boving and Joe Celebrezze"
date: "2023-03-08"
output:
   html_document:
    toc: true
    toc_depth: 4
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
here = here::here
library(tidyverse)
```

# Introduction

This .Rmd file covers the necessary metadata for the datasets that we used in the analyses for the paper, *Pyro-ecophysiology of Sierra Nevada tree and shrub species: flammability, fuel moisture, and water relations mirror fire regime and drought-tolerance strategies* (title pending).

It does so by describing each column of each dataset included in this GitHub. For more information on the organization of the GitHub or which scripts are responsible for which analyses, see the README file included on the GitHub. Many variables/columns are repeated on multiple datasets, and in these cases we do not describe them again, as this would be redundant; however, we try to make it clear where repeated columns exist and why.

This metadata was last updated on:
**March 8, 2023** by **Joe Celebrezze**

--------------------------

# Raw Data
