---
title: 'Model Comparison: EPI vs. HP design
author: "Indra Boving"
date: "04/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(ggplot2)
#install.packages("gapminder")
library(gapminder)
#install.packages("data.table")
library(data.table)
#install.packages("purrr")
library(purrr) #for visualizing all variables in one big plot
#install.packages("naniar")
library(naniar)
library(dplyr)
library(tidyverse)
library(devtools)
#install_github("vqv/ggbiplot", force = TRUE)
library(ggbiplot)
#install.packages("ggfortify")
library(ggfortify)
library(ggpubr)
library(here)
here=here::here
```

```{r echo=FALSE, warning=FALSE}
<<<<<<< HEAD
all.data.hp <- read.csv(here("processed-data/mem.data.seki.hp.csv"))
  
all.data.epi <- read.csv(here("processed-data/mem.data.seki.epi.csv")) 
=======
all.data.hp <- read.csv(here("processed-data/mem.data.seki.hp.csv")) %>%
  mutate(lfm = lfm.NAs.imputed)
  
all.data.epi <- read.csv(here("processed-data/mem.data.seki.epi.csv")) %>%
  mutate(lfm = lfm.NAs.imputed)
>>>>>>> f914d10ea3176bb4d5b372fb6656d2f7a2477b22

all.data <- rbind(all.data.hp, all.data.epi)

write.csv(all.data, here("processed-data/seki.alldata.04.12.2021.csv"))
```
Point:
```{r}
plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = tti, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = fh, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = fd, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = ttfg, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = PC1, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = PC2, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = lfm.NAs.imputed, y = temp.max, color = spp)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot
```

Bins:
```{r}
plot <- ggplot(all.data, aes(x = bins10lfm, y = tti, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = bins10lfm, y = fh, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = bins10lfm, y = fd, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = bins10lfm, y = ttfg, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = bins10lfm, y = PC1, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = bins10lfm, y = PC2, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot

plot <- ggplot(all.data, aes(x = bins10lfm, y = temp.max, color = spp)) + 
  geom_boxplot() +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~model, scales = "free")
plot
```

```{r}
ggplot(data = all.data, mapping =aes(x = spp, y = tti)) +
  geom_boxplot() +
  facet_wrap(~model)

ggplot(data = all.data, mapping =aes(x = spp, y = fh)) +
  geom_boxplot() +
  facet_wrap(~model)

ggplot(data = all.data, mapping =aes(x = spp, y = gd)) +
  geom_boxplot() +
  facet_wrap(~model)
```

Just hot plate: 

Bar charts:
```{r}
str(all.data.hp)
ggplot(all.data.hp) +
  geom_col(aes(x = lfm, y = fh)) +
  scale_x_binned(n.breaks = 16, nice.breaks = TRUE) +
  #facet_wrap(~spp) +
  #scale_x_continuous(lim = c(30, 160), breaks = seq(30,160, by = 10)) +
  facet_wrap(~spp) 

str(all.data.hp)
ggplot(all.data.hp) +
  geom_col(aes(x = lfm, y = fh)) +
  scale_x_binned(n.breaks = 16, nice.breaks = TRUE) 
  #scale_x_continuous(lim = c(30, 160), breaks = seq(30,160, by = 10)) +
  #facet_wrap(~spp) 


ggplot(all.data.hp) +
  geom_col(aes(x = lfm, y = tti)) +
  scale_x_binned(n.breaks = 16, nice.breaks = TRUE) +
  #facet_wrap(~spp) +
  #scale_x_continuous(lim = c(30, 160), breaks = seq(30,160, by = 10)) +
  facet_wrap(~spp) 
```

Time to ignition:
```{r}
str(all.data.hp)
range(all.data.hp$tti)

ggplot(aes(x = lfm, y = tti), data = all.data.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=10 ) +
  facet_wrap(~spp) 

ggplot(aes(x = lfm, y = tti), data = all.data.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=10 ) +
  scale_x_reverse() 

#reduce range to include only realistic values: 

subset.hp <- all.data.hp %>%
  filter(lfm > 50) %>%
  filter(lfm < 150)

ggplot(aes(x = lfm, y = tti), data = subset.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=5 ) +
  facet_wrap(~spp)  +
  scale_x_reverse() 

ggplot(aes(x = lfm, y = tti), data = subset.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=5 ) +
  scale_x_reverse() 
```

```{r}
str(all.data.hp)
range(all.data.hp$gd)

ggplot(aes(x = lfm, y = gd), data = all.data.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=10 ) +
  facet_wrap(~spp) 

ggplot(aes(x = lfm, y = gd), data = all.data.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=10 ) +
  scale_x_reverse() 

#reduce range to include only realistic values: 

subset.hp <- all.data.hp %>%
  filter(lfm > 50) %>%
  filter(lfm < 150)

ggplot(aes(x = lfm, y = gd), data = subset.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=5 ) +
  facet_wrap(~spp)  +
  scale_x_reverse() 

ggplot(aes(x = lfm, y = gd), data = subset.hp) +
  stat_summary_bin(fun.y = "mean", geom="bar", binwidth=5 ) +
  scale_x_reverse() 
```

Binned boxplots:
```{r}
  ggplot(data = subset.hp, mapping =aes(x = lfm, y = tti)) +
  geom_boxplot(mapping = aes(group = cut_width(lfm, 5)))  +
    facet_wrap(~spp)
  
  
ggplot(data = subset.hp, mapping =aes(x = spp, y = tti)) +
  geom_boxplot()
```