source("http://goo.gl/UUyEzD") #outlier KD (original function)

#The following function is derived from outlierKD (from above)
outlierKD2 <- function(dt, var) {
  var.name <- eval(substitute(var),eval(dt))
  tot <- sum(!is.na(var.name))
  na1 <- sum(is.na(var.name))
  m1 <- mean(var.name, na.rm = T)
  par(mfrow=c(2, 2), oma=c(0,0,3,0))
  boxplot(var.name, main="With outliers")
  hist(var.name, main="With outliers", xlab=NA, ylab=NA)
  outlier <- boxplot.stats(var.name)$out
  mo <- mean(outlier)
  var.name <- ifelse(var.name %in% outlier, NA, var.name)
  boxplot(var.name, main="Without outliers")
  hist(var.name, main="Without outliers", xlab=NA, ylab=NA)
  title("Outlier Check", outer=TRUE)
  na2 <- sum(is.na(var.name))
  message("Outliers identified: ", na2 - na1, " from ", tot, " observations")
  message("Proportion (%) of outliers: ", (na2 - na1) / tot*100)
  message("Mean of the outliers: ", mo)
  m2 <- mean(var.name, na.rm = T)
  message("Mean without removing outliers: ", m1)
  message("Mean if we remove outliers: ", m2)
  dt[as.character(substitute(var))] <- invisible(var.name)
  assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
  message("Outliers successfully removed", "\n")
  return(invisible(dt))
}