---
title: "Untitled"
author: "Indra Boving"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pv_allcurves_data <- read.csv(here("processed-data", "allcurves_clean.csv"))

head(pv_allcurves_data)
```

```{r}
pv_allcurves_data %>% 
ggplot(aes(y = neg_mpa, x = rwd)) +
  geom_point() +
  facet_wrap(~spp) +
  th +
  xlim(0, 100)
```

```{r}
quke_pv <- pv_allcurves_data %>% 
  filter(spp %in% c("QUKE"))

quke_pv %>% 
  filter(unique_id == "2020_10_QUKE_4") %>% 
ggplot(aes(y = neg_mpa, x = rwd)) +
  geom_point() +
  facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = (100 - rwc_at_tlp)), size = .5, color = "olivedrab") +
  th +
  xlim(0, 45) +
  ylim(0, 10) +
  labs(y = "-1/MPa", 
       x = "Relative Water Deficit") 

quke_pv %>% 
  filter(year == "2020") %>% 
ggplot(aes(y = neg_mpa, x = rwd)) +
  geom_point() +
  #facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = mean((100 - rwc_at_tlp))), size = .5, color = "olivedrab") +
  th +
  xlim(0, 45) +
  ylim(0, 10) +
  labs(y = "-1/MPa", 
       x = "Relative Water Deficit")
```


```{r}
quke_pv %>% 
  filter(year == "2020") %>% 
ggplot(aes(y = water_potential, x = rwd)) +
  geom_point() +
  #facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = mean((100 - rwc_at_tlp))), size = .5, color = "olivedrab") +
  th +
  #xlim(0, 45) +
  #ylim(0, 10) +
  labs(y = "-MPa", 
       x = "Relative Water Deficit") 
```


```{r}
adfa_pv <- pv_allcurves_data %>% 
  filter(spp %in% c("ADFA"))

adfa_pv %>% 
  filter(year == "2020") %>% 
ggplot(aes(y = neg_mpa, x = rwd)) +
  geom_point() +
  #facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = mean((100 - rwc_at_tlp))), size = .5, color = "olivedrab") +
  th +
  xlim(0, 45) +
  ylim(0, 10) +
  labs(y = "-1/MPa", 
       x = "Relative Water Deficit")
```


```{r}
adfa_pv %>% 
  filter(year == "2020") %>% 
ggplot(aes(y = water_potential, x = rwd)) +
  geom_point() +
  #facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = mean((100 - rwc_at_tlp))), size = .5, color = "olivedrab") +
  th +
  #xlim(0, 45) +
  #ylim(0, 10) +
  labs(y = "-MPa", 
       x = "Relative Water Deficit") 
```


```{r}
ceme_pv <- pv_allcurves_data %>% 
  filter(spp %in% c("CEME"))

ceme_pv %>% 
  filter(year == "2020") %>% 
ggplot(aes(y = neg_mpa, x = rwd)) +
  geom_point() +
  #facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = mean((100 - rwc_at_tlp))), size = .5, color = "olivedrab") +
  th +
  xlim(0, 45) +
  ylim(0, 10) +
  labs(y = "-1/MPa", 
       x = "Relative Water Deficit")
```


```{r}
ceme_pv %>% 
  filter(year == "2020") %>% 
ggplot(aes(y = water_potential, x = rwd)) +
  geom_point() +
  #facet_wrap(~unique_id) +
  geom_vline(aes(xintercept = mean((100 - rwc_at_tlp))), size = .5, color = "olivedrab") +
  geom_hline(aes(yintercept = mean((tlp))), size = .5, color = "olivedrab") +
  th +
  #xlim(0, 45) +
  #ylim(0, 10) +
  labs(y = "-MPa", 
       x = "Relative Water Deficit") 
```

```{r}
pv_allcurves_data %>% 
  ggplot(aes(x = lfm_at_tlp, y = rwc_at_tlp, color = spp)) +
  geom_point() +
  geom_abline() 
```
```{r}
pv_allcurves_data %>% 
  filter(spp %in% c("ADFA", "CEME")) %>% 
  ggplot(aes(x = lfm_at_tlp, y = rwc_at_tlp, color = spp, shape = date)) +
  geom_point() +
  geom_abline() 
```
