For figure with lfm boxplots: 

# Pheno_fig df wrangle

###Our data:
```{r}
pheno_fig <- pheno_df %>% 
  filter(#category %in% c("Leaves", "Needles"), 
         phenophase_status == "Yes") %>% 
  mutate(week = week(date)) %>% 
  select(phenophase_name, date, week, spp) %>% 
   mutate(Species = case_when(
    spp == "ABCO" ~ "A. concolor",
    spp == "PIJE" ~ "P. jeffreyi", 
    spp == "CADE" ~ "C. decurrens", 
    spp == "CECO" ~ "C. cordulatus", 
    spp == "ARPA" ~ "A. patula", 
    spp == "QUKE" ~ "Q. kelloggii"
    ))  %>% 
  mutate(data_source = "mlab")
```

#NPN data: 
```{r}
pheno_fig_npn_raw <- read_csv(here("processed-data", "analysis 2.0", "npn_data.csv"), show_col_types = F) %>% filter(phenophase_status == 1)

pheno_fig_npn <- pheno_fig_npn_raw %>% 
  filter() %>% 
  select(phenophase_description, observation_date, common_name) %>% 
  mutate(date = observation_date,
         year = year(date), 
         month = month(date),
         week = week(date),
         phenophase_name = phenophase_description, 
         data_source = "npn",
         spp = case_when(
           common_name %in% c("white fir") ~ "ABCO", 
           common_name %in% c("incense cedar") ~ "CADE", 
           common_name %in% c("California black oak") ~ "QUKE", 
           common_name %in% c("greenload manzanita") ~ "ARPA", 
           common_name %in% c("whitethord ceanothus") ~ "CECO", 
           common_name %in% c("Jeffrey pine") ~ "PIJE"
         )) %>% 
  drop_na(date) %>% 
  mutate(Species = case_when(
    spp == "ABCO" ~ "A. concolor",
    spp == "PIJE" ~ "P. jeffreyi", 
    spp == "CADE" ~ "C. decurrens", 
    spp == "CECO" ~ "C. cordulatus", 
    spp == "ARPA" ~ "A. patula", 
    spp == "QUKE" ~ "Q. kelloggii"
    )) %>% 
  select(phenophase_name, date, week, spp, Species, data_source)
```

####***Combine NPN and our data: 
```{r}
pheno_fig3 <- bind_rows(pheno_fig_npn, pheno_fig2) %>% 
  mutate(month = month(date), 
         day = mday(date), 
         year = year(date)) %>% 
   mutate(phenophase_name = case_when(
    phenophase_name %in% c("Breaking needle buds (conifers)", "Breaking needle buds", "Breaking leaf buds") ~ "Breaking buds",
    phenophase_name %in% c("Young needles", "Young needles (conifers)","Young leaves", "Young needles (pines)", "Young leaves (tree/shrub)")  ~ "Young leaves",
    phenophase_name %in% c("Emerging needles (pines)","Emerging needles") ~ "Increasing leaf size",
    phenophase_name %in% c("Pollen cones (conifers)", "Pollen cones") ~ "Pollen cones",
    phenophase_name %in% c("Pollen release (flowers)", "Pollen release (conifers)" ,"Pollen release", "Open pollen cones (conifers)" ) ~ "Pollen release",
    phenophase_name == "Increasing leaf size" ~ "Increasing leaf size",
    phenophase_name == "Flowers or flower buds" ~ "Flowers or flower buds",
    phenophase_name %in% c("Ripe fruits", "Fruits") ~ "Fruits",
    phenophase_name == "Ripe fruits" ~ "Ripe fruits", 
    phenophase_name %in% c("Recent cone or seed drop",  "Recent fruit or seed drop") ~ "Recent seed drop",
    TRUE ~ as.character(phenophase_name))) %>% 
  mutate(lfm =  case_when(
    phenophase_name == "Breaking buds" ~ 5,
    phenophase_name == "Young leaves" ~ 10,
    phenophase_name == "Increasing leaf size" ~ 15,
    phenophase_name == "Pollen cones" ~ 20,
    phenophase_name =="Pollen release" ~ 25,
    phenophase_name == "Increasing leaf size" ~ 30,
    phenophase_name == "Flowers or flower buds" ~ 35,
    phenophase_name == "Open flowers" ~ 40,
    phenophase_name == "Fruits" ~ 45,
    phenophase_name == "Ripe fruits" ~50, 
    phenophase_name == "Recent seed drop" ~ 55,
    TRUE ~ NA_real_)) %>% 
  select(year, date, lfm, Species, spp, phenophase_name, week, data_source, month, day)
  
unique(pheno_fig3$phenophase_name)
unique(pheno_fig3$lfm)

```


```{r}
field_data_2021_fig <- field_data_all_3 %>% 
  select(age, year, date, lfm, Species, spp) %>%
  filter(year == 2021,
         age != "both")

field_data_fig_2 <- bind_rows(field_data_2021_fig, pheno_fig3) %>% 
  mutate(year = year(date), 
         doy = day(date))

field_data_2021 <- field_data_fig_2  %>% 
    mutate(age_new = case_when(
    age %in% c("new") & 
      spp %in% c("ABCO") & 
      week %in% c(17, 20, 24)
      ~ "old",
     age %in% c("old") & 
      spp %in% c("CADE") & 
      week > 24
      ~ "new",
    age %in% c("old") & 
      spp %in% c("CECO") & 
      week > 24
      ~ "new",
    age %in% c("new") & 
      spp %in% c("PIJE") & 
      week %in% c(17, 20)
      ~ "old",
     age %in% c("old") & 
      spp %in% c("ARPA") & 
      week > 25
      ~ "new",
    TRUE ~ as.character(age))
  ) %>% 
 drop_na(spp, Species) %>% 
  mutate(age_labs = case_when(
    age_new %in% c("new") ~ "Current Year", 
    age_new %in% c("old") ~ "Previous Year", 
    TRUE ~ as.character(age)
  )
  ) %>% 
  mutate(day = day(date), 
         month = month(date)) %>% 
   mutate(month_char = case_when(
   day < 15 & month == 4 ~ "E. April",
   day > 15 & month == 4 ~ "L. April", 
   day < 15 & month == 5 ~ "E. May",
   day > 15 & month == 5 ~ "L. May",
     day < 15 & month == 6 ~ "E. June",
     day > 15 & month == 6 ~ "L. June",
     day < 15 & month == 7 ~ "E. July",
     day > 15 & month == 7 ~ "L. July",
     day < 15 & month == 8 ~ "E. Aug.",
     day > 15 & month == 8 ~ "L. Aug.",
    day < 15 & month == 9 ~ "E. Sept.",
     day > 15 & month == 9 ~ "L. Sept.",
     day < 15 & month == 10 ~ "E. Oct.",
     day > 15 & month == 10 ~ "L. Oct.", 
   TRUE ~ "NA"#as.character(month)
  )) %>% 
  filter(month_char != "NA")
```

For aspect ratio of phenophases plots:
```{r}
two <- c(1/20, 4)
three <- c(1/13, 3)
four <- c(1/10, 2.75)
```

#Function:
```{r}
pheno.boxplot.vis <- function(species, phenophases, max.y = 350, colors, no.phenophases = two){
  
df1 <- field_data_2021 %>% 
  filter(age != "both",
         lfm < 350, 
         spp == species) 

df1$month_char2 <- factor(df1$month_char, levels = c("E. April", "L. April", "E. May", "L. May", 
                                          "E. June", "L. June","E. July",
                                          "L. July", "E. Aug.", "L. Aug.", "E. Sept.",
                                          "L. Sept.", "E. Oct.", "L. Oct."))

df2 <- field_data_2021 %>% 
  filter(spp == species)
mean_lfm <- mean(df2$mean_lfm_fall_spp)

df3 <- pheno_fig3 %>%
  filter(spp == species) %>% 
  filter(phenophase_name %in% phenophases)

p1 <- ggplot(data = df1, aes(x = month_char, y = lfm)) +
  geom_boxplot(aes(fill = age_labs)) +
  geom_hline(aes(yintercept  = mean_lfm),
             linetype = "dotted") +
  scale_y_continuous(limits = c(0, max.y)) +
  facet_wrap(~spp, labeller = labeller(spp = spp.labs)) +
  theme(axis.ticks.x = element_blank(),
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      size = 16),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 16),
    axis.text.y = element_text(size = 12),
    legend.title = element_text(face = "bold"),
    strip.text = element_text(face = "italic", size = 14),
    legend.position = 'none') +
  labs(y = "Live Fuel Moisture",
       fill = "Tissue Status")

p2 <- ggplot2::ggplot(data = df3, aes(x = date, y = lfm, color = phenophase_name)) +
  geom_line(alpha = 1, size = no.phenophases[2]) +
  scale_color_manual(values = colors) +
  theme(aspect.ratio = no.phenophases[1],
        legend.position = 'none',
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = 'white'))

p3 <- p1 + annotation_custom(ggplotGrob(p2), xmin = "E. April", xmax = "L. Oct.",
                       ymin = -10, ymax = 30)
return(p3)
  }
```


Indra attempt:
```{r}
df4 <- field_data_2021 %>% 
  drop_na(phenophase_name)

df5 <- field_data_2021 %>% 
  drop_na(age)

ggplot(data = field_data_2021) +
  geom_boxplot(data = df4,
             aes(x = month_char, 
                y = lfm,
                 fill = age_labs)) +
  geom_hline(aes(yintercept  = mean_lfm),
             linetype = "dotted") +
  geom_line(aes(y = lfm, 
                x = month_char, 
                color = as.factor(phenophase_name)), 
            data = df5) +
  scale_y_continuous(limits = c(0, 260)) +
  facet_wrap( ~ spp, labeller = labeller(spp = spp.labs)) +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      size = 16
    ),
    axis.title.y = element_text(face = "bold", size = 16),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_blank(),
    legend.title = element_text(face = "bold"),
    strip.text = element_text(face = "italic", size = 14),
    legend.position = 'none'
  ) +
  labs(y = "Live Fuel Moisture",
       fill = "Tissue Status")
```

#QUKE:
QUKE wasn't working in the function because of the lack of samples in April
```{r}
df1 <- field_data_2021 %>%
  mutate(month_char = case_when(
    date == '2021-05-14' ~ "May",
    date == '2021-05-15' ~ "May",
    date == '2021-06-15' ~ "June",
    date == '2021-06-16' ~ "June",
    date == '2021-07-08' ~ "E. July",
    date == '2021-07-09' ~ "E. July",
    date == '2021-07-30' ~ "L. July",
    date == '2021-07-31' ~ "L. July",
    date == '2021-08-19' ~ "Aug.",
    date == '2021-08-20' ~ "Aug.",
    date == '2021-09-16' ~ "Sept.",
    date == '2021-09-17' ~ "Sept.",
    date == '2021-10-16' ~ "L. Oct.",
    date == '2021-10-17' ~ "L. Oct."
  )) %>%
  mutate(month_char2 = case_when(
   day < 15 & month == 4 ~ "E. April",
   day > 15 & month == 4 ~ "L. April", 
   day <= 15 & month == 5 ~ "E. May",
   day > 15 & month == 5 ~ "L. May",
     day < 15 & month == 6 ~ "E. June",
     day > 15 & month == 6 ~ "L. June",
     day < 15 & month == 7 ~ "E. July",
     day > 15 & month == 7 ~ "L. July",
     day < 15 & month == 8 ~ "E. Aug.",
     day > 15 & month == 8 ~ "L. Aug.",
    day < 15 & month == 9 ~ "E. Sept.",
     day > 15 & month == 9 ~ "L. Sept.",
     day < 15 & month == 10 ~ "E. Oct.",
     day >= 15 & month == 10 ~ "L. Oct.", 
   TRUE ~ as.character(month_char)
  )) %>% 
  filter(age != "both",
         lfm < 350,
         spp == "QUKE")

df1$month_char2 <- factor(df1$month_char2, levels = c("E. April", "L. April", "E. May", "L. May", 
                                          "E. June", "L. June","E. July",
                                          "L. July", "E. Aug.", "L. Aug.", "E. Sept.",
                                          "L. Sept.", "E. Oct.", "L. Oct."))
df2 <- field_data_all_3 %>% 
  filter(spp == "QUKE")

mean_lfm <- mean(df2$mean_lfm_fall_spp)

df3 <- pheno_fig3 %>%
  filter(spp == "QUKE") #%>% 
  #filter(phenophase_name %in% c("Breaking buds", "Increasing leaf size", "Ripe fruits"))

p1 <- ggplot(data = df1,
             aes(x = month_char, 
                             y = lfm))+
  geom_boxplot(aes(fill = age_labs)) +
  geom_hline(aes(yintercept  = mean_lfm),
             linetype = "dotted") +
  scale_y_continuous(limits = c(0, 260)) +
  facet_wrap( ~ spp, labeller = labeller(spp = spp.labs)) +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      size = 16
    ),
    axis.title.y = element_text(face = "bold", size = 16),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_blank(),
    legend.title = element_text(face = "bold"),
    strip.text = element_text(face = "italic", size = 14),
    legend.position = 'none'
  ) +
  labs(y = "Live Fuel Moisture",
       fill = "Tissue Status")
p1

p2 <- ggplot2::ggplot(data = df3, aes(x = date, y = lfm, color = phenophase_name)) +
  geom_line(alpha = 1, size = 3) +
  scale_color_manual(values = c("lightblue", "darkslategray4", "darkred", "pink", "purple")) +
  theme(aspect.ratio = 1/13,
        legend.position = 'none',
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = 'white'))
p2

p.quke <- p1 + annotation_custom(ggplotGrob(p2), xmin = "E. May", xmax = "L. Oct.",
                       ymin = -10, ymax = 30)
p.quke
```
