---
title: "Untitled"
author: "Indra Boving"
date: "10/31/2022"
output: html_document
---

#Setup:

```{r}
library(here)
library(plyr)
library(tidyverse)
source(here::here("scripts", "scripts_functions", "plot_facet_flam.R"))
source(here::here("scripts", "scripts_functions", "figure_info_sierra_flammability.R"))
library(ggbeeswarm)
library(ggpattern)
library(kableExtra)
#library(sjPlot)
#install.packages("magick")
#install.packages("webshot")
library(webshot)
library(magick)
#webshot::install_phantomjs()
library(kableExtra)
```


```{r}
seg_results_df <- list.files(path = here::here("processed-data", "analysis 2.0", "segmented_reg_all"),  # Identify all CSV files
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows %>% # Combine data sets into one data set 
  mutate(significant = case_when(
    p_value <= 0.05 ~ "yes", 
    p_value > 0.05 ~ "no", 
    TRUE ~ as.character(p_value)
  ))

#reorder so that the flam metrics are in logical order: 
seg_results_df$flam_metric <- factor(seg_results_df$flam_metric, levels = 
                                       c("tti", 
                                         "fh", 
                                         "fd", 
                                         "temp change", 
                                         "gd", 
                                         "prop ignite", 
                                         "lfm temp change" #comment this out once its fixed in processing code
                                         ))
```

#Visualize: 

```{r}
# seg_results_df %>% 
#   ggplot(aes(y = psi, 
#              x = flam_metric
#              )) + 
#   geom_bar(position = "dodge", 
#            stat = identity,
#            aes(fill = analysis)) +
#   #geom_bar(position="dodge", stat="identity") +
#       geom_bar_pattern(#stat = "identity",
#                    pattern_color = "white",
#                    pattern_fill = "black",
#                    aes(pattern = significant)
#                   ) + 
#   facet_wrap(~water_variable, scales = "free") +
#   scale_pattern_manual(values = c("stripe","none")) +
#   scale_fill_discrete(
#     guide = guide_legend(override.aes = list(pattern = "none")) # <- hide pattern
#   )
```


```{r}
for (i in unique(seg_results_df$spp)) {

     df <- seg_results_df %>% 
    filter(spp == i) 

 p <-  ggplot(df,
   aes(
            y = psi, 
             x = flam_metric, 
             fill = analysis, 
            # pattern = as.factor(significant)
             )) + 
   scale_pattern_manual(values = c("yes" = "stripe", "no" = "none", "NA" = "none")) +
  geom_bar(position="dodge", stat="identity") +
 # geom_bar_pattern(position = "dodge", 
          # stat="identity",
    #pattern = "stripe"
   # ) +
  facet_wrap(~water_variable, scales = "free") +
    labs(title = i)
 
 if (!is.null(p)) plot(p)
 
}
```
```{r}
seg_results_df %>% 
  filter(significant == "yes") %>% 
ggplot(
   aes(y = psi, 
             x = flam_metric, 
             fill = spp)) + 
  geom_bar(position="dodge", stat="identity") +

  facet_wrap(~water_variable, scales = "free") +
  color_many
```


#Table: 

LFM: 
```{r}
table_sig_lfm <- seg_results_df %>%
  filter(analysis == "segmented", 
         water_variable == "lfm", 
         #significant =="yes"
         ) %>% 
  #mutate(p_value = cell_spec(p_value, color = ifelse(p_value < 0.05, "green","red"))) %>% 
  #group_by(flam_metric) %>% 
  select(flam_metric, spp, water_variable, psi, st_err, p_value, significant) %>% 
  kbl() %>% 
  kable_paper(full_width = F) 
#%>%
 # column_spec(5, color = ifelse(seg_results_df$p_value > 0.0500001, "red", "green"))

table_sig_lfm


save_kable(table_sig_lfm, here::here("figures", "segmented_tables", "table_sig_lfm.png"))
```

MPa: 
```{r}
table_sig_mpa <- seg_results_df %>%
  filter(analysis == "segmented", 
         water_variable == "mpa", 
         #significant =="yes"
         ) %>% 
  #mutate(p_value = cell_spec(p_value, color = ifelse(p_value < 0.05, "green","red"))) %>% 
  #group_by(flam_metric) %>% 
  select(flam_metric, spp, water_variable, psi, st_err, p_value, significant) %>% 
  kbl() %>% 
  kable_paper(full_width = F) 
#%>%
 # column_spec(5, color = ifelse(seg_results_df$p_value > 0.0500001, "red", "green"))

table_sig_mpa


save_kable(table_sig_mpa, here::here("figures", "segmented_tables", "table_sig_mpa.png"))
```

Only significant rows: 
```{r}
table_sig_mpa <- seg_results_df %>%
  #filter(significant == "yes") %>% 
 # pivot_wider(names_from = analysis, 
           #   values_from = c(psi, st_err, p_value)) %>% 
  filter(significant == "yes") %>% 
  # filter(analysis == "segmented", 
  #        #water_variable == "mpa", 
  #        significant =="yes"
  #        ) %>% 
  #mutate(p_value = cell_spec(p_value, color = ifelse(p_value < 0.05, "green","red"))) %>% 
  #group_by(flam_metric) %>% 
  #select(flam_metric, spp, water_variable, psi, st_err, p_value, significant) %>% 
  kbl() %>% 
  kable_paper(full_width = F) 
#%>%
 # column_spec(5, color = ifelse(seg_results_df$p_value > 0.0500001, "red", "green"))

table_sig_mpa


save_kable(table_sig_mpa, here::here("figures", "segmented_tables", "table_sig_all.png"))

#How many? 
sig_prop_df_sig <- seg_results_df %>%
  filter(significant == "yes", 
         analysis == "segmented") %>% 
  count() %>% 
  pull()

sig_prop_df_all <- seg_results_df %>%
  filter(#significant == "yes", 
         analysis == "segmented") %>% 
  count() %>% 
  pull()

```
