---
title: "Segmented Regressions - Mixed Effects Models"
author: "Indra Boving & Joe Celebrezze"
date: "4/15/2021"
output: html_document
---

#Setup:
```{r}
knitr::opts_chunk$set(echo = TRUE)
#lots of extra here, but oh well___ 
library(ggplot2)
library(gapminder)
library(tidyverse)
library(lme4)
library(here)
library(segmented)
library(nlme)
citation('nlme')
library(lubridate)
#install.packages("plotrix")
library(plotrix)
filter = dplyr::filter
here = here::here
select = dplyr::select
#source(here("source-code", "source-segmented_lme_R"))

# Function to plot mixed effects model segmented regressions:

source(here::here("scripts", "scripts_functions", "plot_segmented_MEM.R"))
```

# Reading in Dataframe
```{r}
seg_data_subset <- read_csv(here("processed-data", "analysis 2.0", "sierra_flam_data_all.csv")) %>% 
  mutate(id = individual)
```

# Color by Season

```{r}
seg_data_subset$color <- 'black'
seg_data_subset$color[seg_data_subset$year_month=='2020_October']="purple"
seg_data_subset$color[seg_data_subset$year_month=='2020_September']="pink"
```

# Splitting by Species and by Sampling Date

```{r} 
seg_data_subset <- seg_data_subset %>% 
  mutate_if(is.character, str_to_lower) %>% 
  mutate(spp = str_trim(spp),
         lfm_scaled = scale(lfm),
    name = paste(spp,"_max", sep = ""), 
    name_subset = paste(spp, "_subset_seg", sep = ""), 
   # name_yearmonth = intersect(spp, year_month), 
    name_yearmonth = paste(spp, year_month, "subset_seg", sep = "_")) 

seg_data_subset %>% 
  group_split(spp) %>%
  setNames(unique(seg_data_subset$name_subset))  %>%
  list2env(envir = globalenv())

seg_dfs <- list(abco_subset_seg, 
                arpa_subset_seg, 
                cade_subset_seg, 
                ceco_subset_seg,
                pije_subset_seg, 
                quke_subset_seg)
 
seg_data_subset %>% 
  group_split(name_yearmonth) %>%
  setNames(unique(seg_data_subset$name_yearmonth))  %>%
  list2env(envir = globalenv())
```


# Maximums for LFM, MPa

```{r}
max_seg_data <- seg_data_subset %>% 
  type.convert(as.is = TRUE) %>% 
  select(mpa, lfm, spp) %>% 
  group_by(spp) %>% 
  summarise(across(where(is.numeric), max, .names = "max_{.col}")) 
```


```{r}
# max_lfm <- max(seg_data_subset$lfm)
# max_mpa <- max(seg_data_subset$mpa)
# 
# list_max <- seg_data_subset %>% 
#   group_by(spp) %>% 
#   summarise(max_lfm = max(lfm), 
#             max_mpa = max(mpa)) %>% 
#   group_split(spp) %>% 
#   setNames(unique(seg_data_subset$name)) 
# 
# list_max %>%
#   list2env(envir = globalenv())
```

# PV Curve Data

```{r}
pv_summary_df_timing <- read_csv(here("processed-data", "pv_summary_df_timing.csv"), show_col_types = FALSE) %>% 
   filter(timing == "fall") %>% 
  mutate_if(is.character, str_to_lower) %>% 
  #mutate_at(spp, str_to_lower) %>% 
  mutate(spp = str_trim(spp),
    name = paste(spp,"_pv", sep = "")) %>% 
  filter(!spp %in% c("ADFA", "CEME"))

pv_summary_df_timing %>% 
  group_split(spp) %>%
   setNames(unique(pv_summary_df_timing$name)) %>%
  list2env(envir = globalenv())

#Dataframe of PV summaries (NOTE: need upper and lower still?)
pv_means <- pv_summary_df_timing %>% 
  type.convert(as.is = TRUE) %>% 
 # select(mpa, lfm, spp, tlp) %>% 
  group_by(spp) %>% 
  summarise(across(where(is.numeric), mean, .names = "mean_{.col}")) 
```

# Run all species (each has its own script)

```{r, warning=FALSE}
list.files("segmented_regressions_species", full.names = TRUE) %>% walk(source)
```

#Final visualizations/summarizing can go here eventually:

```{r}

```

