---
title: "Mixed Effects Models - Time to Ignition"
author: "Indra Boving & Joe Celebrezze"
date: "6/21/2022"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#lots of extra here, but oh well... 
library(ggplot2)
library(gapminder)
library(data.table)
library(purrr) #for visualizing all variables in one big plot
library(naniar) #for dealing with NAs nicely 
library(tidyverse)
library(devtools)
library(ggfortify)
library(ggpubr)
library(jtools)
library(cowplot)
library(lmerTest)
library(ggeffects)  
library(GGally) #for corr plots
require(kimisc) # has the nlist function to create a named list
require(AICcmodavg) # has the aictab function
library(psych)

#devtools::install_github("strengejacke/strengejacke")
library(strengejacke)
library(sjPlot) # table functions
library(sjmisc) # sample data

library(lme4) # fitting models
library(here)
library(effects) #for plotting model effects
library(sjstats) #use for r2 functions
library(TMB)
library(glmmTMB)
library(lattice)
#library(equatiomatic)
library("broom.mixed")
#library(ggbiplot)
select = dplyr::select
here = here::here
library(MuMIn)
library(modelsummary)
library(modelr)
#install_github("BlakeRMills/MetBrewer") 
#library("BlakeRMills/MetBrewer")
#library(memmented)
filter = dplyr::filter
mutate = dplyr::mutate
library(nlme)
library(MetBrewer)
#install.packages("memmented")
#devtools::install_github("hohenstein/remef")
library(remef)
library(kableExtra)

source(here::here("scripts", "scripts_functions", "figure_info_sierra_flammability.R")) #color and theme info is here
```

# Data Wrangling
Because this script used a bunch of datasets from other scripts, I brought in a lot of code from other scripts to ensure that it would run on its own

#MEM DATA
```{r}
mem_data_all_raw <- read_csv(here("processed-data", "sierra_flam_data_all.csv"), show_col_types = F) 

mem_data_all_clean <- mem_data_all_raw %>% 
  select(lfm, mpa, fh, fh, fd, gd,tti, prop_ignite, temp_change, lower_temp_max, ignition, sample_wt, dry_wt, fresh_wt, water_wt, location, site, year_month, spp, individual, bins10lfm, bins5lfm, bins20lfm, notes_flam) %>% 
  mutate(mpa = -1*mpa) %>% 
  mutate(dw_flam_sample = sample_wt * (dry_wt/fresh_wt),
         ww_flam_sample = sample_wt * (water_wt/fresh_wt)) %>% 
  mutate(excess_water = (ww_flam_sample - dw_flam_sample)) %>% 
  #dplyr::group_by(spp) %>% 
  mutate(mpa_scaled = scale(mpa),
         dw_flam_sample_scaled = scale(dw_flam_sample), 
         sample_wt_scaled = scale(sample_wt), 
         ww_flam_sample_scaled = scale(ww_flam_sample),
         lfm_scaled = scale(lfm), 
         excess_water_scaled = scale(excess_water)) %>% 
  mutate(Species = case_when(
    spp == "arpa" ~ "Ar. patula", 
    spp == "abco" ~ "Ab. concolor",
    spp == "cade" ~ "Ca. decurrens",
    spp == "ceco" ~ "Ce. cordulatus",
    spp == "pije" ~ "Pi. jeffreyi",
    spp == "quke" ~ "Qu. kelloggii"
  )) %>% 
  mutate(F.Group = case_when(
    spp == "arpa" ~ "Angiosperm", 
    spp == "abco" ~ "Gymnosperm",
    spp == "cade" ~ "Gymnosperm",
    spp == "ceco" ~ "Angiosperm",
    spp == "pije" ~ "Gymnosperm",
    spp == "quke" ~ "Angiosperm"
  )) %>% 
  filter(!year_month %in% c("2021_august")) %>% 
  filter(ignition != 2) %>% # Removing manual ignitions
  drop_na(mpa_scaled, lfm_scaled, sample_wt_scaled) 

mem_data_all_6 <- mem_data_all_clean %>% 
  filter(spp != "ceco") %>% 
  mutate(mpa_scaled = as.numeric(mpa_scaled)) %>% 
  mutate(sample_wt_scaled = as.numeric(sample_wt_scaled)) %>% 
  mutate(lfm_scaled = as.numeric(lfm_scaled))

lowest_fall <- field_data_all_6 %>% 
  filter(#month == 10,
         spp %in% c("cade", "pije", "abco")) %>% 
  summarise(min_mpa = max
            (mpa, na.rm = T))
lowest_fall
```

#FIELD DATA
```{r}
field_data_all_means <- read_csv(here("processed-data","field_data_2020_2021.csv"), show_col_types = FALSE) %>% 
  drop_na(spp) %>% 
  filter(lfm < 350) %>%
    filter(year == 2021,
      age != "both") %>% 
 # filter(age_new == "new") %>% 
  select(spp, lfm, year, month, water_potential, site, wet_weight, unique_id, date, midday, age) %>% 
  filter(wet_weight > 50) %>% #remove weirdly small wet weights
  #group_by(spp) %>% 
  mutate(mpa = water_potential,
    lfm_scaled = c(scale(lfm)), 
    #lfm_scaled = lfm,
     mpa_scaled = c(scale(mpa)), 
    #mpa_scaled = mpa, 
        # mpa = water_potential, 
         year_month = paste(year, month, sep = "_", collapse = NULL),
        # sample_wt_scaled = c(scale(wet_weight)), 
     sample_wt_scaled = 1,
         individual = unique_id, 
         spp = tolower(spp)) %>% 
  mutate(Species = case_when(
    spp == "arpa" ~ "Ar. patula", 
    spp == "abco" ~ "Ab. concolor",
    spp == "cade" ~ "Ca. decurrens",
    spp == "ceco" ~ "Ce. cordulatus",
    spp == "pije" ~ "Pi. jeffreyi",
    spp == "quke" ~ "Qu. kelloggii"
  )) %>% 
  filter(spp != "ceco") %>% 
  drop_na(spp) %>% 
    mutate(week = week(date)) %>% 
    mutate(age_new = case_when(
      age %in% c("new") & spp %in% c("ABCO") & week %in% c(17, 20, 24) ~ "old",
      age %in% c("old") & spp %in% c("CADE") & week > 24 ~ "new",
      age %in% c("old") & spp %in% c("CECO") & week > 24 ~ "new",
      age %in% c("new") & spp %in% c("PIJE") & week %in% c(17, 20) ~ "old",
      age %in% c("old") & spp %in% c("ARPA") & week > 25 ~ "new",
      TRUE ~ as.character(age))) %>% 
    drop_na(spp, Species) %>% 
    mutate(age_labs = case_when(
      age_new %in% c("new") ~ "Current Year",
      age_new %in% c("old") ~ "Previous Year", 
    TRUE ~ as.character(age))) %>% 
  mutate(date = case_when(
    date == '2021-04-24' ~ "04/24",
    date == '2021-05-14' ~ "05/14",
    date == '2021-05-15' ~ "05/14",
    date == '2021-06-15' ~ "06/15",
    date == '2021-06-16' ~ "06/15",
    date == '2021-07-08' ~ "07/8",
    date == '2021-07-09' ~ "07/8",
    date == '2021-07-30' ~ "07/30",
    date == '2021-07-31' ~ "07/30",
    date == '2021-08-19' ~ "08/19",
    date == '2021-08-20' ~ "08/19",
    date == '2021-09-16' ~ "09/16",
    date == '2021-09-17' ~ "09/16",
    date == '2021-10-16' ~ "10/16",
    date == '2021-10-17' ~ "10/16"
  )) %>%
  
  drop_na(lfm_scaled, mpa_scaled, sample_wt_scaled) %>% 
  group_by(spp, month) %>% 
  mutate(lfm_scaled = mean(lfm_scaled)) %>% 
  mutate(mpa_scaled = mean(mpa_scaled)) %>% 
  mutate(sample_wt_scaled = mean(sample_wt_scaled)) %>%
  ungroup()

field_data_all_means$date <- as.Date(field_data_all_means$date, format='%m/%d')
field_data_all_means$Species <- factor(field_data_all_means$Species, levels = c('Ab. concolor',  'Pi. jeffreyi', 'Ca. decurrens', 'Ar. patula', 'Qu. kelloggii'))
field_data_all_means$spp <- factor(field_data_all_means$spp, levels = c("abco", "pije", "cade", "arpa", "quke"))
```


#Legend: 
```{r}
legend <- cowplot::get_legend(mem_data_all %>% 
ggplot(aes(y = tti, x = lfm_scaled, color = Species)) +
  geom_point(alpha = .5)+
  geom_smooth(method = "lm", se = F) +
  color_noceco +
  labs(y = "Live Fuel Moisture (scaled)", 
       x = "Time to Ignition (sec.)") +
  theme(legend.text = element_text(size = 17),  # , face = 'italic'
        legend.title = element_text(size = 20, face = 'bold'),
        legend.key = element_rect(fill = 'white')))
```

#------------

#Scatterplots

####TTI

```{r}
tti_scatterplot.lfm <- mem_data_all %>% 
ggplot(aes(y = tti, x = lfm, color = Species)) +
  geom_point(alpha = .5)+
  geom_smooth(method = "lm", se = F) +
  color_noceco +
  labs(title = "Live Fuel Moisture (%)", 
       y = "Time to Ignition (sec.)") +
  theme(axis.title.x = element_blank(), 
             # axis.text.x = element_blank(),
              # axis.ticks.y.left = element_blank(), 
              # axis.title.y.left = element_blank(),
              # axis.text.y.left = element_blank(),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              axis.title.y = element_text(face = 'bold', size = 18),
              axis.text.y = element_text(size = 12),
              legend.title = element_text(face = 'bold', size = 14),
              legend.text = element_text(face = 'italic',),
             # panel.grid = element_blank(), axis.ticks.x = element_blank(),
              plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
              plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'),
              legend.position = 'none')  +
  annotate(geom = "text", x = -2.5, y = 170, label = 'a',
           fontface = 'bold', size = 10) 
tti_scatterplot.lfm
  
tti_scatterplot.mpa <- mem_data_all %>% 
ggplot(aes(y = tti, x = mpa, color = Species)) +
  geom_point(alpha = .5)+
  geom_smooth(method = "lm", se = F) +
  color_noceco +
  labs(title = "Water Potential (MPa)", 
       #y = "Time to Ignition (sec.)"
       ) +
  # theme(axis.title.x = element_blank(), 
  #            # axis.text.x = element_blank(),
  #             # axis.ticks.y.left = element_blank(), 
  #             # axis.title.y.left = element_blank(),
  #             # axis.text.y.left = element_blank(),
  #            axis.ticks.x = element_blank(),
  #            # axis.text.x = element_blank(),
  #             axis.ticks.y = element_blank(),
  #             axis.title.y = element_blank(),
  #             axis.text.y = element_blank(),
  #            # panel.grid = element_blank(), axis.ticks.x = element_blank(),
  #             plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
  #             plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'),
  #             legend.position = 'none') +
   theme(axis.title.x = element_blank(),
       axis.text.x = element_blank(),
               axis.ticks.x = element_blank(),
              # axis.text.x = element_blank(),
               axis.ticks.y = element_blank(),
               axis.title.y = element_blank(),
               axis.text.y = element_blank(),
               #axis.title.y = element_text(face = 'bold', size = 16),
               #axis.text.y = element_text(size = 12),
              legend.title = element_text(face = 'bold', size = 14),
               legend.text = element_text(face = 'italic',),
              # panel.grid = element_blank(), axis.ticks.x = element_blank(),
               plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
         plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'),
              # plot.margin = unit(c(.2, 0.05, 0.2, 0.1), 'cm'),
               legend.position = 'none')  +
  annotate(geom = "text", x = -10, y = 170, label = 'b',
           fontface = 'bold', size = 10) 
#tti_scatterplot.mpa
```

###Temp
```{r}
temp_scatterplot.lfm <- mem_data_all %>% 
ggplot(aes(y = temp_change, x = lfm, color = Species)) +
  geom_point(alpha = .5)+
  geom_smooth(method = "lm", se = F) +
  color_noceco +
  labs(#title = "Live Fuel Moisture (%)", 
       y = expression(bold('Temp Change ('~degree~'C)'))) +
  theme(axis.title.x = element_blank(), 
             # axis.text.x = element_blank(),
              # axis.ticks.y.left = element_blank(), 
              # axis.title.y.left = element_blank(),
              # axis.text.y.left = element_blank(),
              axis.title.y = element_text(face = 'bold', size = 18),
         axis.text.x = element_text(size = 14),
              axis.text.y = element_text(size = 12),
              legend.title = element_text(face = 'bold', size = 14),
              legend.text = element_text(face = 'italic',),
             # panel.grid = element_blank(), axis.ticks.x = element_blank(),
              plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
              plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'),
              legend.position = 'none')  +
  annotate(geom = "text", x = -2.5, y = 250, label = 'd',
           fontface = 'bold', size = 10) 
temp_scatterplot.lfm
```


```{r}
temp_scatterplot.mpa <- mem_data_all %>% 
ggplot(aes(y = temp_change, x = mpa, color = Species)) +
  geom_point(alpha = .5)+
  geom_smooth(method = "lm", se = F) +
  color_noceco +
  labs(#title = "Water Potential (MPa)", 
       #y = "Time to Ignition (sec.)"
       ) +
  theme(axis.title.x = element_blank(),
             # axis.text.x = element_blank(),
              axis.ticks.y = element_blank(),
              axis.title.y = element_blank(),
              axis.text.y = element_blank(),
              #axis.title.y = element_text(face = 'bold', size = 16),
              #axis.text.y = element_text(size = 12),
              legend.title = element_text(face = 'bold', size = 14),
              legend.text = element_text(face = 'italic',),
        axis.text.x = element_text(size = 14),
             # panel.grid = element_blank(), axis.ticks.x = element_blank(),
              plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
              plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'),
              legend.position = 'none')  +
  annotate(geom = "text", x = -10, y = 250, label = 'e',
           fontface = 'bold', size = 10) 
temp_scatterplot.mpa
```

#----------------------

#Pred plots:

####TTI

```{r}
tti_df <- mem_data_all_6 %>% 
  drop_na(lfm_scaled, sample_wt_scaled, tti, spp)

tti_mod <- lm(tti ~ spp*lfm_scaled + sample_wt_scaled, data = tti_df)
summary(tti_mod)

tti_df <- field_data_all_means %>% 
  modelr::add_predictions(tti_mod) %>% 
   drop_na(pred) 

# To get standard deviations
tti_df_stdev <- field_data_all_means  %>% 
  drop_na(lfm_scaled, sample_wt_scaled, spp) %>% 
  add_predictions(tti_mod)

tti_df_stdev <- tti_df_stdev %>% 
  drop_na(pred) %>% 
  group_by(spp, month) %>% 
  mutate(stdev.pred = sd(pred))

tti_df <- tti_df %>% 
  mutate(stdev.pred = tti_df_stdev$stdev.pred)

tti_pred <- tti_df %>%
  filter(year == 2021) %>% 
  ggplot(aes(y = pred, x = date, color = spp)) +
   geom_point(alpha = 1, size = 2) +
   #geom_smooth(se = F) +
   geom_line() +
  geom_linerange(aes(ymin = pred - 0.5*stdev.pred, ymax = pred + 0.5*stdev.pred)) +
  scale_y_continuous(breaks = c(20, 40, 60, 80, 100, 120)) +
 # ylim(20, 120)+
  # scale_y_continuous(breaks = c(-100, -80, -60, -40, -20, 0)) +
 # ylim(-120, -20)+
    theme(legend.position = "none",
        axis.text.y = element_text(size = 14),
        #axis.text.x = element_text(size = 18, angle = 20),
       # axis.title = element_text(size = 14, face = 'bold'),
        axis.text.x = element_blank(),
       axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
      #  axis.text.y = element_blank(),
       axis.title.y = element_blank(),
      # axis.ticks.y = element_blank(),
      plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
       # title = element_text(size = 14, face = 'bold'),
      plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm')) +
       # plot.margin = unit(c(0.05, 0.1, 0, 0.1), 'cm')) +
    labs(#y = "Ignitability (-1*sec)", 
      # x = "", 
       title = "Predicted Flammability")  +
  annotate(geom = "text", x = as.Date('2023-04-24'), y = 110, label = 'c',
           fontface = 'bold', size = 10) +
    # geom_text(data = subset(labelData, subset = plot == 'tti'),
    #           aes(x, y, label = labs, group = NULL, color = NULL),
    #           size = 12, fontface = 'bold') +
    color_noceco
tti_pred
```

#For labels:
```{r}
x <- as.Date(c(rep('2023-04-24', 5)))
y <- c(-25, 49.5, 49.5, 365, 105)
labs <- c('a', 'b', 'c', ' ', 'd')
plot <- c('tti', 'fh', 'fd', 'mt', 'tc')
labelData <- data.frame(x, y, labs, plot)
```

####Temp change

```{r}
temp_change_df <- mem_data_all_6 %>% 
  drop_na(mpa, lfm, temp_change)

temp_change_mod <- lm(temp_change ~ spp*lfm_scaled +
                           sample_wt_scaled, data = temp_change_df)
summary(temp_change_mod)

temp_change_df <- field_data_all_means %>% 
  modelr::add_predictions(temp_change_mod)
#To get standard deviations
temp_change_df_stdev <- field_data_all_6 %>% 
  add_predictions(temp_change_mod)
temp_change_df_stdev <- temp_change_df_stdev %>% 
  drop_na(pred) %>% 
  group_by(spp, month) %>% 
  mutate(stdev.pred = sd(pred))
temp_change_df <- temp_change_df %>% 
  mutate(stdev.pred = temp_change_df_stdev$stdev.pred)

temp_change_pred <- temp_change_df %>%
  filter(year == 2021) %>% 
  ggplot(aes(y = pred, x = date, color = spp)) +
   geom_point(alpha = 1, size = 2) +
  # geom_smooth(se = F) +
   geom_line() +
    scale_y_continuous(limits = c(0,110), breaks = c(0, 50, 100, 150)) +
 # scale_x_reverse() +
   geom_linerange(aes(ymin = pred - 0.5*stdev.pred, ymax = pred + 0.5*stdev.pred)) +
    theme(legend.position = "none",
          axis.title.x = element_blank(),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14, #angle = 20, 
                                   hjust = 0.5),
       # axis.text.y = element_blank(),
       axis.title.y = element_blank(),
      # axis.ticks.y = element_blank(),
       # axis.title = element_text(size = 14, face = 'bold'),
        plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'))+
    labs(y = "Temp. Change (C)") +
  annotate(geom = "text", x = as.Date('2023-04-24'), y = 107, label = 'f',
           fontface = 'bold', size = 10) +
    # geom_text(data = subset(labelData, subset = plot == 'tc'),
    #           aes(x, y, label = labs, group = NULL, color = NULL),
    #           size = 12, fontface = 'bold') +
    color_noceco
temp_change_pred
```
#------

#Combine: 

```{r}
fig2 <- cowplot::plot_grid(tti_scatterplot.lfm, tti_scatterplot.mpa, tti_pred, 
                                  temp_scatterplot.lfm, temp_scatterplot.mpa, 
                                  temp_change_pred,
                                nrow = 2,
                                ncol = 3,
                                rel_widths = c(1,.9,1), 
                                align = "btlr")
fig2

fig2_legend <- cowplot::plot_grid(fig2, legend,
                               # nrow = 2,
                                ncol = 2,
                                rel_widths = c(1, .2), 
                                align = "btlr")

fig2_legend

ggsave(plot = fig2_legend, here('figures', 'main-figures', 'Fig2_new.jpg'), height = 10, width = 15)
```
#----------------------

#OLD vs. NEW plots: 

```{r}
field_data_all_means %>% 
  ggplot(aes(y = lfm, 
             x = month, 
             color = age )) +
  geom_point(alpha = .5) +
  facet_wrap(~Species)
```

####TTI, Old

```{r}
tti_df_lfm <- mem_data_all_6 %>% 
  drop_na(lfm_scaled, sample_wt_scaled, tti, spp)

tti_mod_lfm <- lm(tti ~ spp*lfm_scaled + sample_wt_scaled, data = tti_df_lfm)
summary(tti_mod_lfm)

tti_df_old <- field_data_all_means %>% 
  filter(age == "old") %>% 
  modelr::add_predictions(tti_mod_lfm) %>% 
   drop_na(pred) 

# To get standard deviations
tti_df_stdev_old <- field_data_all_means  %>% 
  filter(age == "old") %>% 
  drop_na(lfm_scaled, sample_wt_scaled, spp) %>% 
  add_predictions(tti_mod_lfm) %>% 
  drop_na(pred) %>% 
  group_by(spp, month) %>% 
  mutate(stdev.pred = sd(pred))

tti_df_lfm_old <- tti_df_old %>% 
  mutate(stdev.pred = tti_df_stdev_old$stdev.pred) %>%
  group_by(spp, month) %>% 
  mutate(stdev.pred = mean(stdev.pred), 
         pred = mean(pred))
  

tti_pred_old <- tti_df_lfm_old %>%
  filter(year == 2021) %>% 
  ggplot(aes(y = pred, x = date, color = spp)) +
   geom_point(alpha = 1, size = 2) +
   #geom_smooth(se = F) +
   geom_line() +
  geom_linerange(aes(ymin = pred - 0.5*stdev.pred, ymax = pred + 0.5*stdev.pred)) +
  scale_y_continuous(breaks = c(20, 40, 60, 80, 100, 120)) +
 # ylim(20, 120)+
  # scale_y_continuous(breaks = c(-100, -80, -60, -40, -20, 0)) +
 # ylim(-120, -20)+
    theme(legend.position = "none",
        axis.text.y = element_text(size = 14),
        #axis.text.x = element_text(size = 18, angle = 20),
       # axis.title = element_text(size = 14, face = 'bold'),
        axis.text.x = element_blank(),
       axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
      #  axis.text.y = element_blank(),
       axis.title.y = element_blank(),
      # axis.ticks.y = element_blank(),
      plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
       # title = element_text(size = 14, face = 'bold'),
      plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm')) +
       # plot.margin = unit(c(0.05, 0.1, 0, 0.1), 'cm')) +
    labs(#y = "Ignitability (-1*sec)", 
      # x = "", 
       title = "Predicted Flammability")  +
  annotate(geom = "text", x = as.Date('2023-04-24'), y = 110, label = 'c',
           fontface = 'bold', size = 10) +
    # geom_text(data = subset(labelData, subset = plot == 'tti'),
    #           aes(x, y, label = labs, group = NULL, color = NULL),
    #           size = 12, fontface = 'bold') +
    color_noceco
tti_pred_old
```

####TTI, New

```{r}
tti_df_lfm <- mem_data_all_6 %>% 
  drop_na(lfm_scaled, sample_wt_scaled, tti, spp)

tti_mod_lfm <- lm(tti ~ spp*lfm_scaled + sample_wt_scaled, data = tti_df_lfm)
summary(tti_mod_lfm)

tti_df_new <- field_data_all_means %>% 
  filter(age == "new") %>% 
  modelr::add_predictions(tti_mod_lfm) %>% 
   drop_na(pred) 

# To get standard deviations
tti_df_stdev_new <- field_data_all_means  %>% 
  filter(age == "new") %>% 
  drop_na(lfm_scaled, sample_wt_scaled, spp) %>% 
  add_predictions(tti_mod_lfm) %>% 
  drop_na(pred) %>% 
  group_by(spp, month) %>% 
  mutate(stdev.pred = sd(pred))

tti_df_lfm_new <- tti_df_new %>% 
  mutate(stdev.pred = tti_df_stdev_new$stdev.pred) %>%
  group_by(spp, month) %>% 
  mutate(stdev.pred = mean(stdev.pred), 
         pred = mean(pred))
  

tti_pred_new <- tti_df_lfm_new %>%
  filter(year == 2021) %>% 
  ggplot(aes(y = pred, x = date, color = spp)) +
   geom_point(alpha = 1, size = 2) +
   #geom_smooth(se = F) +
   geom_line() +
  geom_linerange(aes(ymin = pred - 0.5*stdev.pred, ymax = pred + 0.5*stdev.pred)) +
  scale_y_continuous(breaks = c(20, 40, 60, 80, 100, 120)) +
 # ylim(20, 120)+
  # scale_y_continuous(breaks = c(-100, -80, -60, -40, -20, 0)) +
 # ylim(-120, -20)+
    theme(legend.position = "none",
        axis.text.y = element_text(size = 14),
        #axis.text.x = element_text(size = 18, angle = 20),
       # axis.title = element_text(size = 14, face = 'bnew'),
        axis.text.x = element_blank(),
       axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
      #  axis.text.y = element_blank(),
       axis.title.y = element_blank(),
      # axis.ticks.y = element_blank(),
      plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
       # title = element_text(size = 14, face = 'bnew'),
      plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm')) +
       # plot.margin = unit(c(0.05, 0.1, 0, 0.1), 'cm')) +
    labs(#y = "Ignitability (-1*sec)", 
      # x = "", 
       title = "Predicted Flammability")  +
  annotate(geom = "text", x = as.Date('2023-04-24'), y = 110, label = 'c',
           fontface = 'bold', size = 10) +
    # geom_text(data = subset(labelData, subset = plot == 'tti'),
    #           aes(x, y, label = labs, group = NULL, color = NULL),
    #           size = 12, fontface = 'bnew') +
    color_noceco
tti_pred_new
```

#Combined:

```{r}
tti_df_oldnew <- bind_rows(tti_df_lfm_new %>% mutate(type = "new"), 
                         tti_df_lfm_old %>% mutate(type = "old"))

tti_pred_new <- tti_df_oldnew %>%
  filter(year == 2021) %>% 
  ggplot(aes(y = pred, x = date, color = spp, shape = type, linetype = type)) +
   geom_point(alpha = 1, size = 2) +
   #geom_smooth(se = F) +
   geom_line() +
  geom_linerange(aes(ymin = pred - 0.5*stdev.pred, ymax = pred + 0.5*stdev.pred)) +
  scale_y_continuous(breaks = c(20, 40, 60, 80, 100, 120)) +
 # ylim(20, 120)+
  # scale_y_continuous(breaks = c(-100, -80, -60, -40, -20, 0)) +
 # ylim(-120, -20)+
    theme(#legend.position = "none",
        axis.text.y = element_text(size = 14),
        #axis.text.x = element_text(size = 18, angle = 20),
       # axis.title = element_text(size = 14, face = 'bnew'),
        axis.text.x = element_blank(),
       axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
      #  axis.text.y = element_blank(),
       axis.title.y = element_blank(),
      # axis.ticks.y = element_blank(),
      plot.title = element_text(hjust = 0.5, face = 'bold', size = 18),
       # title = element_text(size = 14, face = 'bnew'),
      plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm')) +
       # plot.margin = unit(c(0.05, 0.1, 0, 0.1), 'cm')) +
    labs(#y = "Ignitability (-1*sec)", 
      # x = "", 
       title = "Predicted Flammability")  +
  annotate(geom = "text", x = as.Date('2023-04-24'), y = 110, label = 'c',
           fontface = 'bold', size = 10) +
    # geom_text(data = subset(labelData, subset = plot == 'tti'),
    #           aes(x, y, label = labs, group = NULL, color = NULL),
    #           size = 12, fontface = 'bnew') +
    color_noceco
tti_pred_new
```


#For labels:
```{r}
x <- as.Date(c(rep('2023-04-24', 5)))
y <- c(-25, 49.5, 49.5, 365, 105)
labs <- c('a', 'b', 'c', ' ', 'd')
plot <- c('tti', 'fh', 'fd', 'mt', 'tc')
labelData <- data.frame(x, y, labs, plot)
```

####Temp change

```{r}
temp_change_df <- mem_data_all_6 %>% 
  drop_na(mpa, lfm, temp_change)

temp_change_mod <- lm(temp_change ~ spp*lfm_scaled +
                           sample_wt_scaled, data = temp_change_df)
summary(temp_change_mod)

temp_change_df <- field_data_all_means %>% 
  modelr::add_predictions(temp_change_mod)
#To get standard deviations
temp_change_df_stdev <- field_data_all_6 %>% 
  add_predictions(temp_change_mod)
temp_change_df_stdev <- temp_change_df_stdev %>% 
  drop_na(pred) %>% 
  group_by(spp, month) %>% 
  mutate(stdev.pred = sd(pred))
temp_change_df <- temp_change_df %>% 
  mutate(stdev.pred = temp_change_df_stdev$stdev.pred)

temp_change_pred <- temp_change_df %>%
  filter(year == 2021) %>% 
  ggplot(aes(y = pred, x = date, color = spp)) +
   geom_point(alpha = 1, size = 2) +
  # geom_smooth(se = F) +
   geom_line() +
    scale_y_continuous(limits = c(0,110), breaks = c(0, 50, 100, 150)) +
 # scale_x_reverse() +
   geom_linerange(aes(ymin = pred - 0.5*stdev.pred, ymax = pred + 0.5*stdev.pred)) +
    theme(legend.position = "none",
          axis.title.x = element_blank(),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14, #angle = 20, 
                                   hjust = 0.5),
       # axis.text.y = element_blank(),
       axis.title.y = element_blank(),
      # axis.ticks.y = element_blank(),
       # axis.title = element_text(size = 14, face = 'bold'),
        plot.margin = unit(c(.05, 0.05, 0.05, 0.05), 'cm'))+
    labs(y = "Temp. Change (C)") +
  annotate(geom = "text", x = as.Date('2023-04-24'), y = 107, label = 'f',
           fontface = 'bold', size = 10) +
    # geom_text(data = subset(labelData, subset = plot == 'tc'),
    #           aes(x, y, label = labs, group = NULL, color = NULL),
    #           size = 12, fontface = 'bold') +
    color_noceco
temp_change_pred
```
#------

#Combine: 

```{r}
fig2 <- cowplot::plot_grid(tti_scatterplot.lfm, tti_scatterplot.mpa, tti_pred, 
                                  temp_scatterplot.lfm, temp_scatterplot.mpa, 
                                  temp_change_pred,
                                nrow = 2,
                                ncol = 3,
                                rel_widths = c(1,.9,1), 
                                align = "btlr")
fig2

fig2_legend <- cowplot::plot_grid(fig2, legend,
                               # nrow = 2,
                                ncol = 2,
                                rel_widths = c(1, .2), 
                                align = "btlr")

fig2_legend

ggsave(plot = fig2_legend, here('figures', 'main-figures', 'Fig2_new.jpg'), height = 10, width = 15)
```
