---
title: "Visualizations and Summaries - Figures"
author: "Indra Boving & Joe Celebrezze"
date: "6/21/2022"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(ggpubr)
library(cowplot)
#library(strengejacke)
library(sjPlot) # table functions
library(here)
library("broom.mixed")
library(nlme)
library(lme4)
library(remef)
library(kableExtra)

#some weird functions:
filter = dplyr::filter
mutate = dplyr::mutate
select = dplyr::select
here = here::here
group_by = dplyr::group_by

source(here::here("scripts", "scripts_functions", "figure_info_sierra_flammability.R")) #color and theme info is here
```

Goal here is to make a plot that shows flammability over time: 

1. Get a df of field LFM and MPa values
2. Use best lm to predict TTI, FH, and Max temp from corresponding LFM/Mpa
#Data: 
```{r}
field_data_all_6 <- read_csv(here("processed-data", "analysis 2.0","field_data_2020_2021.csv")) %>% 
  select(spp, lfm, year, month, water_potential, site, wet_weight, unique_id, date) %>% 
  mutate(lfm_scaled = scale(lfm), 
         mpa_scaled = scale(water_potential), 
         mpa = water_potential, 
         year_month = paste(year, month, sep = "_", collapse = NULL), 
         sample_wt_scaled = scale(wet_weight), 
         individual = unique_id, 
         spp = tolower(spp)) %>% 
  filter(spp != "ceco") %>% 
  drop_na(spp)
```

#TTI

```{r}
#tti_mod <- lmer(tti ~ spp*mpa_scaled + spp*lfm_scaled + site + year_month + sample_wt_scaled + (1 | individual), data = mem_data_all)
#summary(tti_mod)
#str(mem_data_all)

tti_mod <- lm(tti ~ spp*mpa_scaled + spp*lfm_scaled 
              +site
              , data = mem_data_all)
summary(tti_mod)

tti_df <- field_data_all_6 %>% 
  modelr::add_predictions(tti_mod)

tti_pred <- tti_df %>% 
  filter(year == 2021) %>% 
ggplot() +
  geom_beeswarm(aes(y = pred*-1, 
                 x = date, 
                 color = spp)) +
  geom_smooth(aes(y = pred*-1, x = date, color = spp)) +
  theme(legend.position = "none") +
  labs(y = "Ignitability") +
  color_many
tti_pred
```

#FH:
```{r}
fh_mod <- lm(fh ~ spp*mpa_scaled + spp*lfm_scaled 
             + site
            # + sample_wt_scaled, 
             ,data = mem_data_all)

fh_df <- field_data_all_6 %>% 
  modelr::add_predictions(fh_mod)

fh_pred <- fh_df %>% 
  filter(year == 2021) %>% 
ggplot() +
  geom_beeswarm(aes(y = pred, 
                 x = date, 
                 color = spp)) +
  geom_smooth(aes(y = pred, x = date, color = spp)) +
  theme(legend.position = "none") +
  labs(y = "Flame Height")+
  color_many
fh_pred
```

#Temp change

```{r}
temp_mod <- lm(temp_change ~ spp*mpa_scaled + spp*lfm_scaled 
              +  site 
             # + year_month 
              #+ sample_wt_scaled 
              #+ (1 | individual)
              , data = mem_data_all)

temp_df <- field_data_all_6 %>% 
  modelr::add_predictions(temp_mod)

temp_pred <- temp_df %>% 
  filter(year == 2021) %>% 
ggplot() +
  geom_beeswarm(aes(y = pred, 
                 x = date, 
                 color = spp)) +
  geom_smooth(aes(y = pred, x = date, color = spp)) +
  theme(legend.position = "none") +
  labs(y = "Temp Change")+
  color_many
temp_pred
```

##Combine together: 

```{r}
leg_plot<- temp_df %>% 
ggplot() +
  geom_point(aes(y = pred, 
                 x = date, 
                 color = spp)) +
  geom_smooth(aes(y = pred, x = date, color = spp))+
  color_many
```

```{r, fig.height= 4, fig.width=2.5}
legend <- cowplot::get_legend(leg_plot)

plots <- cowplot::plot_grid(tti_pred, fh_pred, temp_pred,
                                   ncol = 1
                                   , rel_heights = c(1, 1, 1)
                                   )

legend_plots <- cowplot::plot_grid(plots, legend, ncol = 2, rel_widths = c(4,1))
legend_plots
```

#-------
#boxplots: 

#TTI

```{r}
#tti_mod <- lmer(tti ~ spp*mpa_scaled + spp*lfm_scaled + site + year_month + sample_wt_scaled + (1 | individual), data = mem_data_all)
#summary(tti_mod)
#str(mem_data_all)

tti_mod <- lm(tti ~ spp*mpa_scaled + spp*lfm_scaled + sample_wt_scaled, data = mem_data_all)
summary(tti_mod)

tti_df <- field_data_all_6 %>% 
  modelr::add_predictions(tti_mod)


df_mean <- tti_df %>% 
  group_by(spp) %>% 
  summarize(average = -1*mean(pred)) %>%
  ungroup()

tti_pred <- tti_df %>% 
  filter(year == 2021, 
         month < 10) %>% 
ggplot() +
  geom_boxplot(aes(y = pred*-1, 
                 x = cut(date, breaks = "quarter"),
                 fill = spp)) +
  # geom_line(aes(y = pred*-1, 
  #               #x = cut(date, breaks = "quarter"),
  #               color = spp)) +
  #geom_line(data = df_mean,
           # mapping = aes(x = cut(date, breaks = "quarter"),
                         # y = average)) +
  theme(legend.position = "none") +
  labs(y = "Ignitability", x = "") +
  color_many
tti_pred
```

#FH:
```{r}
fh_mod <- lm(fh ~ spp*mpa_scaled + spp*lfm_scaled 
             + site
            # + sample_wt_scaled, 
             ,data = mem_data_all)

fh_df <- field_data_all_6 %>% 
  modelr::add_predictions(fh_mod)

fh_pred <- fh_df %>% 
  filter(year == 2021, 
         month < 10) %>% 
ggplot() +
  geom_boxplot(aes(y = pred*-1, 
                 x = cut(date, breaks = "quarter"),
                 fill = spp)) +
 # geom_smooth(aes(y = pred*-1, x = date, color = spp)) +
  theme(legend.position = "none") +
  labs(y = "Flame Height", x = "")+
  color_many
fh_pred
```

#Temp change

```{r}
temp_mod <- lm(temp_change ~ spp*mpa_scaled + spp*lfm_scaled 
              +  site 
             # + year_month 
              + sample_wt_scaled 
              #+ (1 | individual)
              , data = mem_data_all)

temp_df <- field_data_all_6 %>% 
  modelr::add_predictions(temp_mod)

temp_pred <- temp_df %>% 
  filter(year == 2021, 
         month < 10) %>% 
ggplot() +
  geom_boxplot(aes(y = pred*-1, 
                 x = cut(date, breaks = "quarter"),
                 fill = spp)) +
 # geom_smooth(aes(y = pred*-1, x = date, color = spp)) +
  theme(legend.position = "none") +
  labs(y = "Temp Change", x = "Date")

temp_pred
```

##Combine together: 

```{r}
leg_plot_box<- temp_df %>% 
ggplot() +
  geom_boxplot(aes(y = pred, 
                 x = date, 
                 fill = spp))
```

```{r, fig.height= 4, fig.width=2.5}
legend_box <- cowplot::get_legend(leg_plot_box)

plots_box <- cowplot::plot_grid(tti_pred, fh_pred, temp_pred,
                                   ncol = 1
                                   , rel_heights = c(2, 1, 1)
                                   )

legend_plots_box <- cowplot::plot_grid(plots_box, legend_box, ncol = 2, rel_widths = c(4,1))
legend_plots_box
```

#-------
#just sept: 

```{r}
field_data_all_sept <- field_data_all_6 %>% 
  filter(month %in% c(9), 
         year == 2021)
```

#ALL together:

```{r}
tti_mod <- lm(tti ~ spp*mpa_scaled + spp*lfm_scaled 
             # + sample_wt_scaled, 
              ,data = mem_data_all)


fh_mod <- lm(fh ~ spp*mpa_scaled + spp*lfm_scaled 
             + site
            # + sample_wt_scaled 
             ,data = mem_data_all)

temp_mod <- lm(temp_change ~ spp*mpa_scaled + spp*lfm_scaled 
              +  site 
             # + year_month 
             # + sample_wt_scaled 
              #+ (1 | individual)
              , data = mem_data_all)


fd_mod <- lm(fd ~ spp*mpa_scaled + spp*lfm_scaled 
              +  site 
             # + year_month 
             # + sample_wt_scaled 
              #+ (1 | individual)
              , data = mem_data_all)


tti_df <- field_data_all_6 %>% 
  modelr::add_predictions(tti_mod) %>% 
  mutate(pred_tti = pred, 
         .keep = "unused")

tti_fh_df <- tti_df %>% 
  modelr::add_predictions(fh_mod) %>% 
  mutate(pred_fh = pred, 
         .keep = "unused")

tti_fh_temp_df <- tti_fh_df %>% 
  modelr::add_predictions(temp_mod) %>% 
  mutate(pred_temp = pred, 
         .keep = "unused")

tti_fh_temp_fd_df <- tti_fh_temp_df %>% 
  modelr::add_predictions(fd_mod) %>% 
  mutate(pred_fd = pred, 
         .keep = "unused")

pred_long_df <- tti_fh_temp_fd_df %>% 
  pivot_longer(cols = c(pred_temp, pred_tti, pred_fh, pred_fd),
                        names_to = "metric", 
               values_to = "prediction"
               )

pred_long_df$spp <- factor(pred_long_df$spp, levels = c("quke", "arpa", "abco", "pije", "cade"))

pred_long_df %>% 
  ggplot(aes(y = prediction, 
             #x = metric, 
             fill = spp)) +
  geom_boxplot() +
  facet_wrap(~metric, scales = "free", nrow = 1)
```



